name: virtual_wallet_core

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  freezed_annotation: any
  uuid: ^3.0.5


dev_dependencies:
  build_runner: any
  freezed: any
  test: ^1.14.4
  mockito: ^4.1.1